# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'simplecov'
SimpleCov.start

require File.expand_path('../fakewebs', __FILE__)
require 'travian'
require 'timecop'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.filter_run_excluding :online unless config.filter_manager.inclusions[:all]

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

def fakeweb_page(filename)
  path = File.expand_path("../fakeweb_pages", __FILE__) + "/#{filename}.html"
end

def load_login_data(hub_host)
  Nokogiri::HTML(File.read(fakeweb_page "#{hub_host}_serverLogin.php"))
end

def load_servers_login_data(hub_host)
  data = load_login_data(hub_host)
  servers_selector(data)
end

def servers_selector(data)
  data.css('div[class~="server"]')
end
